Write-Host "============= Choose =============="
Write-Host "`ta. [1] pour déployer des VMs en précisant chaque paramètre"
Write-Host "`tb. [2] pour déployer un nombre précis de VMs avec les mêmes paramètres"
Write-Host "`tc. [3] pour déployer des VMs depuis un CSV"
Write-Host "`tc. [4] pour stopper les VMs d'un RG"
Write-Host "`tc. [5] pour télécharger un fichier RDP d'une VM"
Write-Host "`td. [6] to Quit'"
Write-Host "========================================================"
$menu_choice = Read "Enter Choice"
